class Config:
    SECRET_KEY = "your_secret_key_here"
    DEBUG = True
    MONGO_URI = "mongodb://localhost:27017/ToaruIF"  # Update with your MongoDB URI

    # ToaruIF Client Data
    RES_VER = 145545
    TAG_SCHEDULE = 14250
    APP_VER = "6.3.0"
    CDN_ENABLE = 1
    SPECIALBG_ENABLE = 0
    TITLEID = 0
    TITLE_BACKGROUND_ENABLE = 1
    SMARTBEAT_ENABLE = 0
    LOGIN_URL = "https://login.index-if.jp/Auth/"
    RES_URL = "http://cache.index-if.jp/ver2/"  # "https://192.168.1.179:40443/ver2/"
    WEB_URL = "https://192.168.1.217:40443/web/"
    API_URL = "https://login.index-if.jp/api/"

    # ToaruIF Server Config
    IS_CRYPT = 1  # 0 is sending pure JSON and client will send pure json, 1 is sending/receiving encrypted data
    TUTORIAL_BYPASS = True # This lets you bypass the tutorial and having everything ready.
    CREATE_WITH_EVERYTHING = True # This adds you all the cards provided by the game database (BattleCard and AssistCard)

    # ToaruIF Server constants
    GAME_CONSTS = {
        "arena_class_actionsv_replay_expire_day": 10,
        "arena_play_shortcut_need_pay_point": 10,
        "arena_play_heal_need_pay_point1": 50,
        "arena_play_heal_need_pay_point2": 60,
        "arena_play_heal_need_pay_point3": 70,
        "arena_play_heal_need_pay_point4": 80,
        "arena_play_heal_need_pay_point5": 90,
        "arena_matching_interval_sec": 1,
        "arena_defend_reward_arena_money": 10,
        "arena_trinity_play_shortcut_need_pay_point": 10,
        "arena_trinity_play_heal_need_pay_point1": 50,
        "arena_trinity_play_heal_need_pay_point2": 60,
        "arena_trinity_play_heal_need_pay_point3": 70,
        "arena_trinity_play_heal_need_pay_point4": 80,
        "arena_trinity_play_heal_need_pay_point5": 90,
        "arena_trinity_matching_interval_sec": 1,
        "arena_trinity_defend_reward_arena_money": 10,
        "arena_class_tournament_prediction_limit_hour": 5,
        "webview_login_information": 1,
        "paypoint_max": 9999999,
        "date_change_hour": 5,
        "retry_request_flag_enable": 1,
        "bridge_paypoint_free_max": 9999999,
        "card_awaken_status_lottery_max": 10,
        "card_duplicate_limit_break_item_num_n": 5,
        "card_duplicate_limit_break_item_num_r": 30,
        "card_duplicate_limit_break_item_num_sr": 100,
        "card_duplicate_limit_break_item_num_ssr": -1,
        "card_duplicate_limit_break_item_num_ur": -1,
        "card_exchange_need_material_num_n": 15,
        "card_exchange_need_material_num_r": 45,
        "card_exchange_need_material_num_sr": 145,
        "card_exchange_need_material_num_ssr": -1,
        "card_exchange_need_material_num_ur": -1,
        "card_limit_break_money_base": 1000,
        "card_limit_break_money_rarity_add_rate": 20,
        "card_pair_bonus_rate_hp": 10500,
        "card_pair_bonus_rate_str": 10500,
        "card_pair_bonus_rate_inte": 10500,
        "card_pair_bonus_rate_vit": 10500,
        "card_pair_bonus_rate_mind": 10500,
        "card_pair_bonus_rate_dex": 10500,
        "card_pair_bonus_rate_agi": 10500,
        "card_power_hp_rate": 2000,
        "card_power_attack_rate": 5000,
        "card_power_defence_rate": 5000,
        "card_power_dex_rate": 8000,
        "card_power_dex_rate2": 60000,
        "card_power_normal_skill_rate": 50000,
        "card_power_special_skill_rate": 50000,
        "card_power_assist_skill_rate": 50000,
        "card_power_potential_skill_rate": 50000,
        "card_rank_exp_rate_rarity_n": 100,
        "card_rank_exp_rate_rarity_r": 100,
        "card_rank_exp_rate_rarity_sr": 100,
        "card_rank_exp_rate_rarity_ssr": 100,
        "card_rank_exp_rate_rarity_ur": 100,
        "card_status_type_node_rate": 40,
        "chara_present_favorite_rate": 200,
        "chara_meet_shortcut_min": 10,
        "chara_meet_shortcut_min_paypoint": 10,
        "deck_trinity_type_arena_trinity_defence_deck_pair_max": 6,
        "deck_trinity_type_arena_trinity_attack_deck_pair_max": 6,
        "dungeon_pay_play_need_pay_point": 50,
        "dugeon_reward_ticket": 1,
        "use_event_boss_ticket_normal": 20,
        "use_event_boss_ticket_hard": 30,
        "use_event_boss_ticket_very_hard": 30,
        "use_event_boss_ticket_very_hard_no_limit": 30,
        "use_event_point_event_gacha_box": 1,
        "use_event_gacha_bilibili_num": 1,
        "event_boss_normal_story_skip_use_ticket_num": 1,
        "event_boss_hard_story_skip_use_ticket_num": 1,
        "event_boss_very_hard_story_skip_use_ticket_num": 1,
        "event_boss_very_hard_no_limit_story_skip_use_ticket_num": 1,
        "use_event_gacha_bilibili_challenge_num": 1,
        "event_total_beat_count_update_time": 10,
        "event_raid_refresh_need_pay_point1": 0,
        "event_raid_refresh_need_pay_point2": 0,
        "event_raid_refresh_need_pay_point3": 0,
        "event_raid_refresh_need_pay_point4": 0,
        "event_raid_refresh_need_pay_point5": 0,
        "event_raid_refresh_need_pay_point6": 0,
        "event_raid_refresh_need_pay_point7": 0,
        "event_raid_refresh_need_pay_point8": 0,
        "event_raid_refresh_need_pay_point9": 0,
        "event_raid_refresh_need_pay_point10": 0,
        "event_raid_refresh_count_max": 20,
        "event_raid_battle_max": 10,
        "event_raid_get_event_rescue_raid_list_interval_sec": 1,
        "guild_rank_max": 5,
        "user_guild_exp_point_max": 10000,
        "guild_search_num": 20,
        "guild_search_interval": 1,
        "guild_scout_expired_time": 604800,
        "guild_scouting_search_active_time": 259200,
        "guild_scouting_search_num": 20,
        "guild_scouting_search_interval": 1,
        "guild_scouting_general_max": 15,
        "guild_leader_change_becomes_possible_day": 30,
        "guild_favorite_count": 1,
        "guild_favorite_get_stamina": 10,
        "guildchat_get_list_interval": 5,
        "guildchat_get_list_max": 200,
        "guildchat_get_list_retry_interval": 1,
        "guildchat_submit_interval": 1,
        "guild_login_member_num_reward_receieve_day": 7,
        "guild_battle_quest_member_max": 0,
        "guild_battle_raid_play_daily_max": 3,
        "guild_battle_damage_log_get_interval": 5,
        "guild_battle_league_prediction_limit_hour": 16,
        "item_limit_break_sell_rate_n": 2,
        "item_limit_break_sell_rate_r": 2,
        "item_limit_break_sell_rate_sr": 2,
        "item_limit_break_sell_rate_ssr": -1,
        "item_limit_break_sell_rate_ur": -1,
        "item_limit_break_event_sell_rate_n": 1,
        "item_limit_break_event_sell_rate_r": 1,
        "item_limit_break_event_sell_rate_sr": 1,
        "item_limit_break_event_sell_rate_ssr": -1,
        "item_limit_break_event_sell_rate_ur": -1,
        "item_sell_num_max": 99999,
        "statusup_item_exchange_rate": 5,
        "statusup_ticket_sell_rate": 1000,
        "limited_point_story_hard_mode_play_max": 3,
        "limited_point_story_book_grow_play_max": 3,
        "limited_point_event_story_hard_mode_play_max": 3,
        "limited_point_event_boss_very_hard_mode_play_max": 1,
        "missionpass_purchase_reactivate_hours": 72,
        "purchase_shop_lineup_missionpass_buy_warning_hour": 4,
        "recapture_battle_game_limit_time_sec": 1200,
        "recapture_battle_force_unlock_time_sec": 600,
        "recapture_battle_deck_battle_max": 2,
        "recapture_battle_deck_character_bonus_max": 6,
        "recapture_battle_hard_deck_battle_max": 1,
        "record_daily_login_hour1": 12,
        "record_daily_login_hour2": 18,
        "run_game_play_need_play_point": 1,
        "run_game_life_point_start": 3,
        "run_game_life_point_max": 3,
        "run_game_score_rate_fever": 3,
        "run_game_score_bread_get": 10,
        "run_game_score_bread_ex_get": 500,
        "run_game_score_life_get": 100,
        "run_game_score_life_get_by_life_max": 1000,
        "run_game_score_enemy_kill": 300,
        "run_game_score_stage_clear": 100,
        "shop_lineup_normal_update_time1": 5,
        "shop_lineup_normal_update_time2": 13,
        "shop_lineup_normal_update_time3": 21,
        "shop_limit_break_start_price": 2,
        "shop_limit_break_add_price": 2,
        "shop_limit_break_buy_count1": 20,
        "shop_limit_break_buy_count2": 20,
        "shop_limit_break_buy_count3": 20,
        "shop_limit_break_buy_count4": 20,
        "shop_limited_shop_open_minute": 30,
        "shop_limited_shop_open_max": 10,
        "shop_republish_shop_reset_popup_day": 3,
        "shop_recapture_shop_reset_popup_day": 3,
        "spot_update_need_pay_point1": 10,
        "spot_update_need_pay_point2": 10,
        "spot_update_need_pay_point3": 30,
        "spot_update_need_pay_point4": 30,
        "spot_update_need_pay_point5": 50,
        "spot_update_need_pay_point6": 50,
        "spot_update_need_pay_point7": 70,
        "spot_update_need_pay_point8": 70,
        "spot_update_need_pay_point9": 90,
        "spot_update_need_pay_point10": 90,
        "story_skip_use_max": 99,
        "story_original_challenge_point_need_stamina": 200,
        "story_original_need_challenge_point_normal": 1,
        "story_original_need_challenge_point_hard": 2,
        "user_rank_max": 162,
        "magic_rank_max": 50,
        "science_rank_max": 50,
        "chara_rank_max": 100,
        "card_status_rank_max": 67,
        "assist_card_status_rank_max": 67,
        "money_max": 999999999,
        "money_dungeon_max": 99999999,
        "money_arena_max": 99999999,
        "money_quest_max": 99999999,
        "money_limit_break_piece_max": 99999999,
        "money_event_point_max": 99999999,
        "money_event_boss_ticket_max": 99999999,
        "money_raid_beat_max": 99999999,
        "money_raid_rescue_max": 99999999,
        "money_arena_trinity_max": 99999999,
        "money_guild_max": 99999999,
        "money_guild_battle_max": 99999999,
        "money_event_guild_battle_raid_max": 99999999,
        "money_event_gacha_bilibili_max": 99999999,
        "money_event_world_point_max": 99999999,
        "money_republish_max": 99999999,
        "money_event_shop_max": 99999999,
        "money_raid_spawn_ticket_max": 99999999,
        "money_raid_ex_spawn_ticket_max": 99999999,
        "money_recapture_max": 99999999,
        "money_stamina_trade_ticket_max": 99999999,
        "money_arena_class_max": 99999999,
        "money_vote_ticket_max": 99999,
        "money_event_gacha_bilibili_challenge_max": 99999999,
        "inventory_item_max": 999999,
        "stamina_point_max": 999,
        "stamina_heal_need_pay_point": 100,
        "stamina_use_item_num_max": 99,
        "stamina_heal_count1": 1,
        "stamina_heal_count2": 4,
        "stamina_heal_count3": 8,
        "stamina_heal_count4": 16,
        "stamina_heal_need_pay_point1": 40,
        "stamina_heal_need_pay_point2": 100,
        "stamina_heal_need_pay_point3": 180,
        "stamina_heal_need_pay_point4": 250,
        "recapture_coin_reset_convert_reward_type": 4,
        "recapture_coin_reset_convert_rate": 100,
    }
