def getLimitedPointsData(userId: int) -> list:
    # TODO proper logic
    return [
        {
            "type": 2,
            "id": 0,
            "point": 984,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 300,
            "interval_point": 1,
            "point_max": 157,
        },
        {
            "type": 3,
            "id": 0,
            "point": 30,
            "point_next_time": 1562616000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 30,
        },
        {
            "type": 5,
            "id": 0,
            "point": 10,
            "point_next_time": 1562616000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 10,
        },
        {
            "type": 6,
            "id": 0,
            "point": 1,
            "point_next_time": 1657569600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 7,
            "id": 0,
            "point": 1,
            "point_next_time": 1562616000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 8,
            "id": 0,
            "point": 5,
            "point_next_time": 1657569600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 5,
        },
        {
            "type": 9,
            "id": 0,
            "point": 300,
            "point_next_time": 1678305600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1500,
        },
        {
            "type": 10,
            "id": 27,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 28,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 29,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 10,
            "id": 30,
            "point": 5,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 5,
        },
        {
            "type": 10,
            "id": 31,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 32,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 10,
            "id": 33,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 34,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 35,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 36,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 37,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 10,
            "id": 38,
            "point": 5,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 5,
        },
        {
            "type": 10,
            "id": 39,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 40,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 41,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 10,
            "id": 42,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 43,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 44,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 45,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 46,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 10,
            "id": 47,
            "point": 5,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 5,
        },
        {
            "type": 10,
            "id": 48,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 49,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 50,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 51,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 10,
            "id": 52,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 53,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 54,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 55,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 56,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 57,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 10,
            "id": 58,
            "point": 5,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 5,
        },
        {
            "type": 10,
            "id": 59,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 60,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 10,
            "id": 61,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 62,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 63,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 64,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 10,
            "id": 65,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 66,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 67,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 68,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 10,
            "id": 69,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 70,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 71,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 72,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 73,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 74,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 10,
            "id": 75,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 76,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 77,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 78,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 82,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 10,
            "id": 83,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 84,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 85,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 86,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 87,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 88,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 89,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 90,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 118,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 120,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 121,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 1001001,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 1002001,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 1003001,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 1006001,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 1016001,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 10,
            "id": 1017001,
            "point": 1,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 11,
            "id": 100010181,
            "point": 3,
            "point_next_time": 1595188800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010182,
            "point": 3,
            "point_next_time": 1598990400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010183,
            "point": 3,
            "point_next_time": 1595188800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010184,
            "point": 3,
            "point_next_time": 1595188800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010281,
            "point": 3,
            "point_next_time": 1619294400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010282,
            "point": 3,
            "point_next_time": 1601236800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010283,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010284,
            "point": 3,
            "point_next_time": 1599940800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010381,
            "point": 3,
            "point_next_time": 1601236800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010382,
            "point": 3,
            "point_next_time": 1596225600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010383,
            "point": 3,
            "point_next_time": 1596225600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010384,
            "point": 3,
            "point_next_time": 1601236800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010481,
            "point": 3,
            "point_next_time": 1596312000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010482,
            "point": 3,
            "point_next_time": 1596312000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010483,
            "point": 3,
            "point_next_time": 1601236800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010484,
            "point": 3,
            "point_next_time": 1596312000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010581,
            "point": 3,
            "point_next_time": 1597348800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010582,
            "point": 3,
            "point_next_time": 1597348800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010583,
            "point": 3,
            "point_next_time": 1597348800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010584,
            "point": 3,
            "point_next_time": 1598299200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010681,
            "point": 3,
            "point_next_time": 1598299200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010682,
            "point": 3,
            "point_next_time": 1613505600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010683,
            "point": 3,
            "point_next_time": 1611259200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010684,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010781,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010782,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010783,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010784,
            "point": 3,
            "point_next_time": 1613332800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010881,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010882,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010883,
            "point": 3,
            "point_next_time": 1613419200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010884,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010981,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010982,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010983,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100010984,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100011081,
            "point": 3,
            "point_next_time": 1670529600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100011082,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100011083,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100011084,
            "point": 3,
            "point_next_time": 1611604800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 100011181,
            "point": 3,
            "point_next_time": 1613505600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400250281,
            "point": 3,
            "point_next_time": 1598212800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400250282,
            "point": 3,
            "point_next_time": 1598212800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400250283,
            "point": 3,
            "point_next_time": 1598212800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400250284,
            "point": 3,
            "point_next_time": 1598212800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400250285,
            "point": 3,
            "point_next_time": 1598212800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400340281,
            "point": 3,
            "point_next_time": 1597262400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400340282,
            "point": 3,
            "point_next_time": 1597262400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400340283,
            "point": 3,
            "point_next_time": 1597262400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400340284,
            "point": 3,
            "point_next_time": 1597262400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400340285,
            "point": 3,
            "point_next_time": 1597262400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400380281,
            "point": 3,
            "point_next_time": 1605816000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400380282,
            "point": 3,
            "point_next_time": 1605816000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400380283,
            "point": 3,
            "point_next_time": 1605816000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400380284,
            "point": 3,
            "point_next_time": 1605816000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400380285,
            "point": 3,
            "point_next_time": 1605816000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400390281,
            "point": 3,
            "point_next_time": 1599854400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400390282,
            "point": 3,
            "point_next_time": 1599854400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400390283,
            "point": 3,
            "point_next_time": 1599854400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400390284,
            "point": 3,
            "point_next_time": 1599854400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400390285,
            "point": 3,
            "point_next_time": 1599854400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400400281,
            "point": 3,
            "point_next_time": 1600632000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400400282,
            "point": 3,
            "point_next_time": 1600632000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400400283,
            "point": 3,
            "point_next_time": 1600632000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400400284,
            "point": 3,
            "point_next_time": 1600632000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400400285,
            "point": 3,
            "point_next_time": 1600632000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400450281,
            "point": 3,
            "point_next_time": 1610481600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400450282,
            "point": 3,
            "point_next_time": 1610481600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400450283,
            "point": 3,
            "point_next_time": 1610481600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400450284,
            "point": 3,
            "point_next_time": 1610481600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400450285,
            "point": 3,
            "point_next_time": 1610481600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400480281,
            "point": 3,
            "point_next_time": 1612382400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400480282,
            "point": 3,
            "point_next_time": 1612382400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400480283,
            "point": 3,
            "point_next_time": 1612382400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400480284,
            "point": 3,
            "point_next_time": 1612382400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400480285,
            "point": 3,
            "point_next_time": 1612987200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400540281,
            "point": 3,
            "point_next_time": 1623096000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400540282,
            "point": 3,
            "point_next_time": 1623096000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400540283,
            "point": 3,
            "point_next_time": 1623096000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400540284,
            "point": 3,
            "point_next_time": 1623096000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400540285,
            "point": 3,
            "point_next_time": 1623096000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400570281,
            "point": 3,
            "point_next_time": 1621713600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400570282,
            "point": 3,
            "point_next_time": 1621713600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400570283,
            "point": 3,
            "point_next_time": 1621713600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400570284,
            "point": 3,
            "point_next_time": 1621713600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400570285,
            "point": 3,
            "point_next_time": 1621713600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400600281,
            "point": 3,
            "point_next_time": 1628712000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400600282,
            "point": 3,
            "point_next_time": 1628712000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400600283,
            "point": 3,
            "point_next_time": 1628712000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400600284,
            "point": 3,
            "point_next_time": 1628712000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400600285,
            "point": 3,
            "point_next_time": 1628712000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400780281,
            "point": 3,
            "point_next_time": 1659470400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400780282,
            "point": 3,
            "point_next_time": 1659470400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400780283,
            "point": 3,
            "point_next_time": 1659556800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400780284,
            "point": 3,
            "point_next_time": 1659556800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400780285,
            "point": 3,
            "point_next_time": 1659556800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400820281,
            "point": 3,
            "point_next_time": 1657569600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400820282,
            "point": 3,
            "point_next_time": 1657569600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400820283,
            "point": 3,
            "point_next_time": 1657569600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400820284,
            "point": 3,
            "point_next_time": 1657569600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 400820285,
            "point": 3,
            "point_next_time": 1657569600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450180281,
            "point": 3,
            "point_next_time": 1612036800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450180282,
            "point": 3,
            "point_next_time": 1612036800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450180283,
            "point": 3,
            "point_next_time": 1612036800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450180284,
            "point": 3,
            "point_next_time": 1612036800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450180285,
            "point": 3,
            "point_next_time": 1612036800,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450200281,
            "point": 3,
            "point_next_time": 1613851200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450200282,
            "point": 3,
            "point_next_time": 1613851200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450200283,
            "point": 3,
            "point_next_time": 1614283200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450280281,
            "point": 3,
            "point_next_time": 1621886400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450280282,
            "point": 3,
            "point_next_time": 1621886400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450280283,
            "point": 3,
            "point_next_time": 1621886400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450280284,
            "point": 3,
            "point_next_time": 1621886400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450280285,
            "point": 3,
            "point_next_time": 1621886400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450310281,
            "point": 3,
            "point_next_time": 1627329600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450580281,
            "point": 3,
            "point_next_time": 1658520000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450580282,
            "point": 3,
            "point_next_time": 1658520000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450580283,
            "point": 3,
            "point_next_time": 1658520000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450580284,
            "point": 3,
            "point_next_time": 1658520000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 11,
            "id": 450580285,
            "point": 3,
            "point_next_time": 1658520000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 12,
            "id": 3210100,
            "point": 3,
            "point_next_time": 1677787200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 12,
            "id": 3210200,
            "point": 3,
            "point_next_time": 1677787200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 12,
            "id": 3210300,
            "point": 3,
            "point_next_time": 1677787200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 3,
        },
        {
            "type": 13,
            "id": 30,
            "point": 981,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 999999,
        },
        {
            "type": 13,
            "id": 33,
            "point": 1028,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 999999,
        },
        {
            "type": 13,
            "id": 47,
            "point": 1244,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 999999,
        },
        {
            "type": 13,
            "id": 49,
            "point": 788,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 999999,
        },
        {
            "type": 13,
            "id": 59,
            "point": 625,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 999999,
        },
        {
            "type": 13,
            "id": 63,
            "point": 860,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 999999,
        },
        {
            "type": 13,
            "id": 83,
            "point": 810,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 999999,
        },
        {
            "type": 14,
            "id": 0,
            "point": 20,
            "point_next_time": 1562616000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 20,
        },
        {
            "type": 16,
            "id": 0,
            "point": 0,
            "point_next_time": 1678305600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 500,
        },
        {
            "type": 17,
            "id": 0,
            "point": 5,
            "point_next_time": 1657483200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 5,
        },
        {
            "type": 18,
            "id": 0,
            "point": 1,
            "point_next_time": 1658520000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 19,
            "id": 0,
            "point": 0,
            "point_next_time": 1678305600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1200,
        },
        {
            "type": 20,
            "id": 21005,
            "point": 1,
            "point_next_time": 1601496000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 20,
            "id": 21017,
            "point": 1,
            "point_next_time": 1648411200,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 20,
            "id": 21500,
            "point": 1,
            "point_next_time": 1596225600,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
        {
            "type": 24,
            "id": 0,
            "point": 3,
            "point_next_time": 0,
            "extra_point": 0,
            "interval_sec": 3600,
            "interval_point": 1,
            "point_max": 3,
        },
        {
            "type": 21,
            "id": 0,
            "point": 400,
            "point_next_time": 1727640000,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 199800,
        },
        {
            "type": 23,
            "id": 2700,
            "point": 5,
            "point_next_time": 1727294400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 99999,
        },
        {
            "type": 4,
            "id": 0,
            "point": 0,
            "point_next_time": 1727294400,
            "extra_point": 0,
            "interval_sec": 0,
            "interval_point": 0,
            "point_max": 1,
        },
    ]
